import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/provider/convex-client-provider";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "./boards/_components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <Toaster
            style={{
              backgroundColor: "white",
            }}
          />
          <div className="flex flex-col gap-5 p-5">
            <Navbar />
            {children}
          </div>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
